name: CI/CD

on:
  push:
    branches:
      - master # Changing the branch here would also work

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - working-directory: client
        run: npm install
      - working-directory: client
        run: npm run build --if-present
  
#   test:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [10.x, 12.x, 14.x, 15.x, 18.x]
#     steps:
#       - uses: actions/checkout@v3
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v3
#         with:
#           node-version: ${{ matrix.node-version }}
#       - working-directory: client
#         run: npm test
    

#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
#         with:
#           heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#           heroku_app_name: "assignment-2-12-gjchow-ranachi" #Must be unique in Heroku
#           heroku_email: ${{secrets.HEROKU_EMAIL}}
#           appdir: "server"
#           usedocker: true
